#!/usr/bin/env python3
"""hello-squelette — replay one governed change from start to finish, in a temporary copy.

    python3 -B examples/hello-squelette/demo.py            # replay and print the transcript
    python3 -B examples/hello-squelette/demo.py --write    # replay, then refresh TRANSCRIPT.md and the README block
    python3 -B examples/hello-squelette/demo.py --check    # replay, then fail if TRANSCRIPT.md or the README block drifted

The checkout you run it from is never modified: only ``--write`` rewrites the two files named
above. Everything else happens in a temporary directory that is deleted at the end.
Standard library only. The demo plays both roles — a scripted Project Owner who answers the
FIRST_START interview, and an agent who runs the controller — so that every line of output
below comes from a real run of ``scripts/project_control.py``.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]  # examples/hello-squelette/ -> repository root
TRANSCRIPT = HERE / "TRANSCRIPT.md"
README = ROOT / "README.md"
BEGIN = "<!-- hello-squelette:begin -->"
END = "<!-- hello-squelette:end -->"
CONTROL = "scripts/project_control.py"
OWNER = "Project Owner"
GIT_IDENTITY = {"GIT_AUTHOR_NAME": "hello-squelette", "GIT_AUTHOR_EMAIL": "hello@squelette.invalid",
                "GIT_COMMITTER_NAME": "hello-squelette", "GIT_COMMITTER_EMAIL": "hello@squelette.invalid",
                "GIT_OPTIONAL_LOCKS": "0"}
EXCERPT_KEYS = ("status_in_progress", "preflight_refused", "status_done")


# --------------------------------------------------------------------------- transcript

class Transcript:
    """Collects sections, narration and command runs; renders Markdown; normalizes volatile values."""

    def __init__(self, root: Path, verbose: bool = False) -> None:
        self.root = root
        self.verbose = verbose
        self.entries: list[dict] = []
        self.by_key: dict[str, dict] = {}

    def section(self, title: str) -> None:
        self.entries.append({"kind": "section", "title": title})

    def say(self, text: str) -> None:
        self.entries.append({"kind": "text", "text": text})

    def run(self, args: list[str], *, key: str | None = None, expect: int = 0, shown: str | None = None,
            cwd: Path | None = None, env_extra: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
        env = dict(os.environ)
        env.update(GIT_IDENTITY)
        if env_extra:
            env.update(env_extra)
        completed = subprocess.run(args, cwd=cwd or self.root, check=False, capture_output=True, text=True, env=env)
        output = (completed.stdout + completed.stderr).rstrip()
        entry = {"kind": "cmd", "command": shown or " ".join(shell_quote(a) for a in args),
                 "output": output, "exit": completed.returncode}
        self.entries.append(entry)
        if key:
            self.by_key[key] = entry
        if expect == 0 and completed.returncode != 0:
            raise RuntimeError(f"unexpected failure: {entry['command']}\n{output}")
        if expect != 0 and completed.returncode == 0:
            raise RuntimeError(f"expected a refusal, got success: {entry['command']}\n{output}")
        return completed

    def control(self, *args: str, key: str | None = None, expect: int = 0) -> subprocess.CompletedProcess[str]:
        return self.run([sys.executable, "-B", CONTROL, *args], key=key, expect=expect,
                        shown="python3 -B " + CONTROL + " " + " ".join(shell_quote(a) for a in args))

    def git(self, *args: str, key: str | None = None, expect: int = 0) -> subprocess.CompletedProcess[str]:
        return self.run(["git", *args], key=key, expect=expect, shown="git " + " ".join(shell_quote(a) for a in args))

    # rendering ---------------------------------------------------------------

    def render_entry(self, entry: dict) -> str:
        lines = [f"$ {entry['command']}"]
        if entry["output"]:
            lines.append(entry["output"] if self.verbose else fold_pass_lines(entry["output"]))
        if entry["exit"] != 0:
            lines.append(f"[exit {entry['exit']}]")
        return "\n".join(lines)

    def render_full(self) -> str:
        out = ["# hello-squelette — transcript of one governed change",
               "",
               "Generated by `python3 -B examples/hello-squelette/demo.py --write` from a real run of the",
               "controller in a temporary copy of this template. Volatile values are replaced by placeholders",
               "(`<commit>`, `<sha256>`, `<date>`, `<timestamp>`, `<demo>`) and each run of `PASS:` control lines",
               "is folded into a count (`--verbose` keeps them); everything else is the controller's actual output.",
               "`tests/test_template.py` replays the demo and fails if this file or the README block drifts from",
               "what the controller really prints.",
               ""]
        block: list[str] = []

        def flush() -> None:
            if block:
                out.append("```text")
                out.extend(block)
                out.append("```")
                out.append("")
                block.clear()

        for entry in self.entries:
            if entry["kind"] == "section":
                flush()
                out.append(f"## {entry['title']}")
                out.append("")
            elif entry["kind"] == "text":
                flush()
                out.append(entry["text"])
                out.append("")
            else:
                if block:
                    block.append("")
                block.append(self.render_entry(entry))
        flush()
        return self.normalize("\n".join(out).rstrip() + "\n")

    def render_excerpt(self) -> str:
        parts = [self.render_entry(self.by_key[key]) for key in EXCERPT_KEYS]
        return self.normalize("```text\n" + "\n\n".join(parts) + "\n```\n")

    def normalize(self, text: str) -> str:
        text = text.replace(str(self.root), "<demo>")
        text = re.sub(r"\b[0-9a-f]{64}\b", "<sha256>", text)
        text = re.sub(r"\b[0-9a-f]{40}\b", "<commit>", text)
        text = re.sub(r"(?m)^([|/\\ *]*)[0-9a-f]{7,12}(?= )", r"\1<sha>", text)
        text = re.sub(r"\(([0-9a-f]{7,12})\)", "(<sha>)", text)
        text = re.sub(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})", "<timestamp>", text)
        text = re.sub(r"\b\d{4}-\d{2}-\d{2}\b", "<date>", text)
        text = re.sub(r"Ran (\d+) tests? in [0-9.]+s", r"Ran \1 tests in <duration>", text)
        return text


def fold_pass_lines(output: str) -> str:
    """Fold each run of two or more `PASS: …` control lines into one line, so that refusals stay visible."""
    folded: list[str] = []
    run: list[str] = []

    def flush() -> None:
        if len(run) == 1:
            folded.append(run[0])
        elif run:
            folded.append(f"… {len(run)} controls PASS …")
        run.clear()

    for line in output.splitlines():
        if line.startswith("PASS: "):
            run.append(line)
            continue
        flush()
        folded.append(line)
    flush()
    return "\n".join(folded)


def shell_quote(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_./=:@%+,-]+", value):
        return value
    return '"' + value.replace('"', '\\"') + '"'


# --------------------------------------------------------------------------- helpers

def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def dump_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def load_controller(root: Path):
    spec = importlib.util.spec_from_file_location("hello_squelette_project_control", root / CONTROL)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


def tracked_files(source: Path) -> list[Path]:
    """The template's tracked tree, without .git (a fresh project never inherits the template's history)."""
    if (source / ".git").exists():
        env = dict(os.environ, GIT_OPTIONAL_LOCKS="0")
        listed = subprocess.run(["git", "ls-files", "-z"], cwd=source, check=True, capture_output=True, env=env)
        return [source / name for name in listed.stdout.decode("utf-8").split("\0") if name]
    return [path for path in sorted(source.rglob("*"))
            if path.is_file() and ".git" not in path.parts and "__pycache__" not in path.parts]


def export_template(source: Path, target: Path) -> list[str]:
    names = []
    for path in tracked_files(source):
        relative = path.relative_to(source)
        if relative.parts[:2] == ("examples", "hello-squelette") and relative.name == "TRANSCRIPT.md":
            continue
        # A new project starts without the template's own generated roadmap view: keeping it
        # would make this demo depend on the state of the repository it is replayed from.
        if relative.parts[0] == "provenance" and (
            relative.name == "ROADMAP_VIEW.md" or relative.parts[:2] == ("provenance", "roadmap")
        ):
            continue
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, destination)
        names.append(str(relative))
    return names


def replace_once(path: Path, pattern: str, replacement: str) -> None:
    text = path.read_text(encoding="utf-8")
    updated, count = re.subn(pattern, replacement, text, count=1)
    if count != 1:
        raise RuntimeError(f"pattern not found in {path}: {pattern}")
    path.write_text(updated, encoding="utf-8")


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# --------------------------------------------------------------------------- the story

CHARTER = """# Project Charter

Status: `VALIDATED`

`PROJECT_OWNER: Project Owner`

## Purpose and Expected Outcome

Hello Squelette greets whoever runs it. The project exists to show one governed change
from authorization to proof, in a few minutes, on a project small enough to read entirely.

## Users and Consumers

Anyone who clones the template and wants to see how an agent works under Squelette.

## Scope

A greeting function under `modules/hello/` with its tests. Nothing else.

## Non-Goals

No billing, no persistence, no network, no deployment. A change outside `modules/hello/`
needs a new Work Item authorized by the Project Owner.
"""

ARCHITECTURE_MAP = """# Project Architecture Map

Status: `VALIDATED`

| Question | Status |
|---|---|
| Ownership explicit? | PASS |
| Boundaries explicit? | PASS |

`modules/hello/` is the only component. It has no dependency and no consumer yet.

ANTI_OCTOPUS_REVIEW: APPROVED_BY_PROJECT_OWNER
"""

INITIAL_ARCHITECTURE = """# Initial Architecture

Status: `VALIDATED`

One module, `modules/hello/`, exposing `greet(name)`. Tests live next to it.
"""

ADR_0001 = """# ADR-0001 — Initial architecture boundaries

Status: `ACCEPTED`

One module and its tests. Any second component is a new decision.
"""

HD_001 = """
## HD-001

Date: {date}
Decision: Validate the Charter, the initial architecture and the Anti-Octopus review; authorize the initialization Work Item WI-000 and close FIRST_START.
Context: Scripted FIRST_START interview of the hello-squelette demo.
Options considered: AUTHORIZE | REJECT
Chosen option: AUTHORIZE
Reason: The project is small enough to read entirely; its scope and non-goals are explicit.
Scope: Initialization of the project; reporting style PLAIN.
Reversible: NO
Conversation reference: CONV-000
Related ADR: ADR-0001
Related Work Item: WI-000
Folder scope: NOT_APPLICABLE
Authorized by: Project Owner
"""

GREETING_PY = '''"""Greeting module of the hello-squelette demo (authorized by WI-001)."""


def greet(name: str = "Squelette") -> str:
    return f"Hello, {name}!"
'''

TEST_GREETING_PY = '''import unittest

from greeting import greet


class GreetingTests(unittest.TestCase):
    def test_default_greeting(self) -> None:
        self.assertEqual(greet(), "Hello, Squelette!")

    def test_named_greeting(self) -> None:
        self.assertEqual(greet("Ada"), "Hello, Ada!")


if __name__ == "__main__":
    unittest.main()
'''

SNEAKY_PY = '''"""Nobody authorized a billing module. The preflight must refuse this path."""
TAX_RATE = 0.2
'''


def scripted_interview(root: Path, control_module) -> None:
    """The Project Owner's answers to FIRST_START, written where an agent would write them in Bootstrap Mode."""
    base_head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, check=True, capture_output=True,
                               text=True, env=dict(os.environ, GIT_OPTIONAL_LOCKS="0")).stdout.strip()
    state_path = root / "project_control/project-state.v1.json"
    state = load_json(state_path)
    state.update(repository_role="PROJECT", project_name="Hello Squelette", project_key="HELLO",
                 project_owner=OWNER, reporting_style="PLAIN", language="EN")
    state["initialization"]["completion_human_decision_ref"] = "HD-001"
    dump_json(state_path, state)

    (root / "docs/governance/PROJECT_CHARTER.md").write_text(CHARTER, encoding="utf-8")
    (root / "docs/architecture/PROJECT_ARCHITECTURE_MAP.md").write_text(ARCHITECTURE_MAP, encoding="utf-8")
    (root / "docs/architecture/INITIAL_ARCHITECTURE.md").write_text(INITIAL_ARCHITECTURE, encoding="utf-8")
    (root / "docs/adr/ADR-0001-initial-architecture-boundaries.md").write_text(ADR_0001, encoding="utf-8")
    decisions = root / "docs/governance/HUMAN_DECISIONS.md"
    decisions.write_text(decisions.read_text(encoding="utf-8").rstrip() + "\n"
                         + HD_001.format(date=control_module.today_iso()), encoding="utf-8")
    replace_once(root / "docs/governance/REPOSITORY_STATUS.md", r"CANONICAL BRANCH: [^`\n]+", "CANONICAL BRANCH: main")

    work_item = copy.deepcopy(load_json(root / "tests/fixtures/project_control/work-item.valid.json"))
    work_item.pop("close_head", None)
    work_item.update(
        work_item_id="WI-000", display_reference="HELLO-000", title="Initialize the project",
        objective="Run the FIRST_START interview and record its deliverables.", owner=OWNER,
        status="AUTHORIZED", human_decision_refs=["HD-001"], conversation_refs=["CONV-000"], agent_run_refs=[],
        dependencies=[], base_head=base_head, start_head="UNKNOWN", branch="work/wi-000-initialization",
        commits=[], authorized_paths=["docs/governance", "project_control"], conflict_gate="INDEPENDENT",
        direct_impact=["docs/governance", "project_control"], indirect_impact=["None"],
        authority_impact=["Charter, initial architecture, ADR-0001"], concurrent_work_impact=["NONE"],
        applicability={"code": "NOT_APPLICABLE", "tests": "NOT_APPLICABLE", "integration": "NOT_APPLICABLE",
                       "deployment": "NOT_APPLICABLE", "runtime_proof": "NOT_APPLICABLE"},
        development_status="NOT_APPLICABLE", test_status="NOT_APPLICABLE", integration_status="NOT_APPLICABLE",
        deployment_status="NOT_APPLICABLE", runtime_proof_status="NOT_APPLICABLE",
        evidence={"tests": [], "integration": [], "deployment": [], "runtime_proof": []},
        close_condition="FIRST_START closed and committed.", runtime_target="NOT_APPLICABLE",
    )
    dump_json(root / "project_control/work-items/WI-000.json", work_item)

    conversation = copy.deepcopy(load_json(root / "tests/fixtures/project_control/conversation.valid.json"))
    conversation.update(conversation_ref="CONV-000", provider="hello-squelette demo", title="FIRST_START interview",
                        purpose="Scripted interview of the Project Owner for the hello-squelette demo.",
                        related_work_items=["WI-000"],
                        summary_reference="The interview answers are the governance documents themselves.")
    dump_json(root / "project_control/conversations/CONV-000.json", conversation)

    roadmap_path = root / "docs/governance/roadmap-state.v1.json"
    roadmap = load_json(roadmap_path)
    roadmap["work_items"] = [{"work_item_id": "WI-000", "display_reference": "HELLO-000",
                              "title": "Initialize the project", "status": "AUTHORIZED",
                              "integration_state": "UNMERGED", "human_gate": "HD-001", "dependencies": []}]
    dump_json(roadmap_path, roadmap)
    (root / "docs/governance/ROADMAP.md").write_text(
        "# Roadmap\n\nStatus: `INITIALIZED`\n\n"
        "| Internal ID | Display reference | Work Item | Status | Integration | Human gate | Depends on |\n"
        "|---|---|---|---|---|---|---|\n"
        "| WI-000 | HELLO-000 | Initialize the project | AUTHORIZED | UNMERGED | HD-001 | — |\n",
        encoding="utf-8")
    registry = root / "docs/governance/WORKTREE_REGISTRY.md"
    registry.write_text(control_module.render_registry_entry(registry.read_text(encoding="utf-8"), work_item, "DECLARED"),
                        encoding="utf-8")


def complete_initialization(root: Path, control_module) -> None:
    """After bootstrap-closeout PASS: the explicit NOT_STARTED -> COMPLETE transition, WI-000 closed."""
    head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, check=True, capture_output=True, text=True,
                          env=dict(os.environ, GIT_OPTIONAL_LOCKS="0")).stdout.strip()
    replace_once(root / "FIRST_START.md", r"INITIALIZATION_STATUS: NOT_STARTED", "INITIALIZATION_STATUS: COMPLETE")
    state_path = root / "project_control/project-state.v1.json"
    state = load_json(state_path)
    state["initialization"].update(status="COMPLETE", completed_at=datetime.now(timezone.utc).isoformat(),
                                   baseline_head=head, closeout_evidence=["project_control.py bootstrap-closeout PASS"])
    dump_json(state_path, state)
    item_path = root / "project_control/work-items/WI-000.json"
    item = load_json(item_path)
    item.update(status="DONE", close_head=head)
    dump_json(item_path, item)
    roadmap_path = root / "docs/governance/roadmap-state.v1.json"
    roadmap = load_json(roadmap_path)
    roadmap["work_items"][0].update(status="DONE", integration_state="HISTORICAL")
    dump_json(roadmap_path, roadmap)
    replace_once(root / "docs/governance/ROADMAP.md", r"\| AUTHORIZED \| UNMERGED \|", "| DONE | HISTORICAL |")
    registry = root / "docs/governance/WORKTREE_REGISTRY.md"
    registry.write_text(control_module.render_registry_entry(registry.read_text(encoding="utf-8"), item, "CLOSED"),
                        encoding="utf-8")


def evidence_report(root: Path, work_item_id: str, gate: str, level: str, artifact: Path, summary: str) -> str:
    subject = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, check=True, capture_output=True, text=True,
                             env=dict(os.environ, GIT_OPTIONAL_LOCKS="0")).stdout.strip()
    report = {"schema_version": "1.0.0", "work_item_id": work_item_id, "gate": gate, "result": "PASS",
              "level": level, "subject_commit": subject, "runtime_target": "NOT_APPLICABLE",
              "recorded_at": datetime.now(timezone.utc).isoformat(), "summary": summary,
              "artifacts": [{"path": str(artifact.relative_to(root)), "sha256": sha256_of(artifact)}]}
    path = root / f"reports/evidence/{work_item_id}/{gate}.json"
    dump_json(path, report)
    return str(path.relative_to(root))


def changed_paths(root: Path, files: list[str]) -> list[str]:
    return [name for name in files if (root / name).exists()]


def play(source: Path, work: Path, verbose: bool = False) -> Transcript:
    root = work / "hello-squelette"
    root.mkdir()
    t = Transcript(root, verbose=verbose)

    # 1 ----------------------------------------------------------------------
    t.section("1. A fresh copy of the template becomes a project")
    exported = export_template(source, root)
    # No file count here: the public mirror of the template carries one file fewer than the private
    # repository (its export tool), and a transcript that counted them drifted between the two.
    assert exported, "the template's tracked tree is what the demo copies"
    t.say("The tracked tree of the template is copied without `.git`: a new project starts "
          "its own history. Git is initialized, the pristine copy is committed as the autonomous baseline, then "
          "the commit gate is installed outside the worktree — where no commit can carry it away — and every "
          "commit is audited from now on.")
    t.git("init", "-b", "main")
    t.run(["git", "add", "--", *exported], shown="git add -- <every exported file, explicitly>")
    t.git("commit", "-q", "-m", "init: pristine copy of the template")
    t.control("install-gate", key="install_gate")
    t.control("status", key="status_fresh")

    # 2 ----------------------------------------------------------------------
    t.section("2. Bootstrap Mode: only initialization paths are writable")
    t.say("Before FIRST_START is closed, the controller only accepts the governance files of the interview. "
          "Business code is refused, whatever the agent intends.")
    t.control("bootstrap-audit", key="bootstrap_audit")
    t.control("bootstrap-preflight", "--path", "modules/hello/greeting.py", key="bootstrap_refused", expect=1)
    t.control("bootstrap-preflight", "--path", "docs/governance/PROJECT_CHARTER.md",
              "--path", "docs/governance/HUMAN_DECISIONS.md", "--path", "project_control/work-items/WI-000.json",
              key="bootstrap_allowed")

    # 3 ----------------------------------------------------------------------
    t.section("3. The Project Owner answers the interview; the agent records the answers")
    control_module = load_controller(root)
    scripted_interview(root, control_module)
    t.say("A scripted Project Owner validates the Charter, the initial architecture, ADR-0001 and the "
          "Anti-Octopus review, chooses the `PLAIN` reporting style, and records HD-001, which authorizes the "
          "initialization Work Item WI-000. The agent writes these records, audits them and commits them — the "
          "hook replays `bootstrap-audit` on the staged state before accepting the commit.")
    t.control("bootstrap-audit", key="bootstrap_audit_records")
    interview_files = ["project_control/project-state.v1.json",
                       "docs/governance/PROJECT_CHARTER.md", "docs/architecture/PROJECT_ARCHITECTURE_MAP.md",
                       "docs/architecture/INITIAL_ARCHITECTURE.md",
                       "docs/adr/ADR-0001-initial-architecture-boundaries.md",
                       "docs/governance/HUMAN_DECISIONS.md", "docs/governance/REPOSITORY_STATUS.md",
                       "project_control/work-items/WI-000.json", "project_control/conversations/CONV-000.json",
                       "docs/governance/roadmap-state.v1.json", "docs/governance/ROADMAP.md",
                       "docs/governance/WORKTREE_REGISTRY.md"]
    t.run(["git", "add", "--", *interview_files], shown="git add -- <the interview records, explicitly>")
    t.git("commit", "-q", "-m", "init: FIRST_START interview recorded (HD-001)")
    t.say("The closeout checks every deliverable of the interview at once.")
    t.control("bootstrap-closeout", "--path", "FIRST_START.md", "--path", "project_control/project-state.v1.json",
              key="closeout")
    complete_initialization(root, control_module)
    t.say("`INITIALIZATION_STATUS` goes to `COMPLETE` in FIRST_START.md and in Project State together, WI-000 is "
          "closed, and the transition is committed explicitly. From now on the canonical branch only accepts "
          "administrative records, reports and provenance: this transition commit is the one the hook lets "
          "through only under an explicit human mandate, echoed in the transcript.")
    transition_files = ["FIRST_START.md", "project_control/project-state.v1.json",
                        "project_control/work-items/WI-000.json", "docs/governance/roadmap-state.v1.json",
                        "docs/governance/ROADMAP.md", "docs/governance/WORKTREE_REGISTRY.md"]
    t.run(["git", "add", "--", *transition_files], shown="git add -- <the closeout transition, explicitly>")
    t.run(["git", "commit", "-q", "-m", "init: FIRST_START closed (HD-001)"],
          shown='PROJECT_CONTROL_HOOK_OVERRIDE="HD-001: FIRST_START closeout" git commit -q -m "init: FIRST_START closed (HD-001)"',
          env_extra={"PROJECT_CONTROL_HOOK_OVERRIDE": "HD-001: FIRST_START closeout"}, key="closeout_commit")
    t.control("audit", key="audit_after_init")
    t.control("status", key="status_at_rest")

    # 4 ----------------------------------------------------------------------
    t.section("4. A human decision authorizes one Work Item")
    t.say("The Project Owner decides: add a greeting module under `modules/hello/`, nothing else. "
          "`create-work-item` records the decision HD-002, the Work Item, its conversation reference, the roadmap, "
          "the branch registry and the path classification in one transaction, and commits them itself.")
    t.control("create-work-item", "WI-001",
              "--title", "Greeting module",
              "--objective", "Add greet(name) under modules/hello/ with its tests.",
              "--owner", OWNER,
              "--human-decision", "HD-002",
              "--decision", "Authorize WI-001: a greeting module under modules/hello/, with tests, and nothing else.",
              "--authorized-by", OWNER,
              "--branch", "work/wi-001-greeting",
              "--path", "modules/hello",
              "--conflict-gate", "INDEPENDENT",
              "--direct-impact", "modules/hello",
              "--indirect-impact", "None: the module has no consumer yet",
              "--authority-impact", "NONE",
              "--concurrent-work-impact", "NONE",
              "--code", "APPLICABLE", "--tests", "APPLICABLE", "--integration", "APPLICABLE",
              "--deployment", "NOT_APPLICABLE", "--runtime-proof", "NOT_APPLICABLE",
              "--runtime-target", "NOT_APPLICABLE",
              "--close-condition", "Tests pass and the branch is integrated into main.",
              key="create")

    # 5 ----------------------------------------------------------------------
    t.section("5. The agent proves it has read the authorities, then starts")
    t.say("`context-manifest` lists the documents that govern this Work Item, with their SHA-256 and a global "
          "digest. `start` refuses without that digest, and never prints it in its own output: the agent has to "
          "go and get it from the authorities as they stand right now. What this proves is narrow and exact — the "
          "work started from the current text of every authority, and changing any one of them invalidates the "
          "proof until it is acknowledged again. No mechanism can prove that a mind was changed by reading.")
    manifest = t.control("context-manifest", "WI-001", key="manifest")
    digest = next(line.split(": ", 1)[1].strip() for line in manifest.stdout.splitlines()
                  if line.startswith("MANIFEST_DIGEST: "))
    t.control("start", "WI-001", key="start_refused", expect=1)
    t.control("start", "WI-001", "--authorities-digest", digest, key="start")
    t.control("status", key="status_in_progress")

    # 6 ----------------------------------------------------------------------
    t.section("6. Outside the authorized scope, the preflight refuses")
    t.say("The agent drifts: it writes a billing module nobody asked for and stages it. The preflight names the "
          "path and fails; the hook would refuse the commit for the same reason.")
    sneaky = root / "modules/billing/invoice.py"
    sneaky.parent.mkdir(parents=True)
    sneaky.write_text(SNEAKY_PY, encoding="utf-8")
    t.git("add", "--", "modules/billing/invoice.py")
    t.control("preflight", "WI-001", key="preflight_refused", expect=1)
    t.git("rm", "-q", "--cached", "--", "modules/billing/invoice.py")
    sneaky.unlink()
    sneaky.parent.rmdir()
    t.say("The drift is undone. Inside the authorized scope — the greeting module and its tests, staged with "
          "explicit paths — the same preflight passes.")
    hello = root / "modules/hello"
    hello.mkdir(parents=True)
    (hello / "greeting.py").write_text(GREETING_PY, encoding="utf-8")
    (hello / "test_greeting.py").write_text(TEST_GREETING_PY, encoding="utf-8")
    t.git("add", "--", "modules/hello/greeting.py", "modules/hello/test_greeting.py")
    t.control("preflight", "WI-001", "--path", "modules/hello/greeting.py", "--path", "modules/hello/test_greeting.py",
              key="preflight_pass")

    # 7 ----------------------------------------------------------------------
    t.section("7. Work, tests, integration")
    tests = t.run([sys.executable, "-B", "-m", "unittest", "discover", "-s", "modules/hello", "-p", "test_*.py"],
                  shown="python3 -B -m unittest discover -s modules/hello -p 'test_*.py'", key="tests")
    t.git("commit", "-q", "-m", "feat(hello): greeting module (WI-001)")
    feature_commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, check=True, capture_output=True,
                                    text=True, env=dict(os.environ, GIT_OPTIONAL_LOCKS="0")).stdout.strip()
    t.git("switch", "-q", "main")
    t.git("merge", "--no-ff", "-q", "-m", "merge: integrate WI-001", "work/wi-001-greeting")

    # 8 ----------------------------------------------------------------------
    t.section("8. Evidence, then close")
    t.say("Each applicable gate needs a JSON report pointing at a committed artifact with its SHA-256, for the "
          "exact integrated commit. `close` verifies the reports, the declared business commit, the branch "
          "integration and the proof of reading, then records `DONE` and commits.")
    evidence_dir = root / "reports/evidence/WI-001"
    evidence_dir.mkdir(parents=True)
    tests_artifact = evidence_dir / "tests.txt"
    tests_artifact.write_text((tests.stdout + tests.stderr), encoding="utf-8")
    integration_artifact = evidence_dir / "integration.txt"
    log = subprocess.run(["git", "log", "--oneline", "-3"], cwd=root, check=True, capture_output=True, text=True,
                         env=dict(os.environ, GIT_OPTIONAL_LOCKS="0")).stdout
    integration_artifact.write_text("Integrated into main by a no-fast-forward merge:\n" + log, encoding="utf-8")
    tests_report = evidence_report(root, "WI-001", "tests", "TESTED", tests_artifact,
                                   "unittest discover on modules/hello: all tests pass.")
    integration_report = evidence_report(root, "WI-001", "integration", "INTEGRATED", integration_artifact,
                                         "Branch work/wi-001-greeting merged into main.")
    t.run(["git", "add", "--", tests_report, integration_report, "reports/evidence/WI-001/tests.txt",
           "reports/evidence/WI-001/integration.txt"], shown="git add -- reports/evidence/WI-001/*")
    t.git("commit", "-q", "-m", "evidence: WI-001 tests and integration")
    t.control("close", "WI-001", "--commit", feature_commit,
              "--test-evidence", tests_report, "--integration-evidence", integration_report, key="close")
    t.say("The roadmap view — what happened, what is next, what waits for the Project Owner — is generated from "
          "the records, in the reporting style the Project Owner chose; the controller commits the Markdown view "
          "itself, the HTML page is ignored by Git.")
    t.control("roadmap-view", "--write", key="roadmap_view")
    t.control("status", key="status_done")
    t.control("audit", key="audit_done")
    t.git("log", "--oneline", "--graph", key="log")
    t.say("Every administrative step is a commit of its own, made by the controller on the canonical branch. "
          "The project is at rest again: no active Work Item, one proven change, a readable history.")
    return t


# --------------------------------------------------------------------------- entry point

def readme_block(text: str) -> tuple[int, int] | None:
    begin = text.find(BEGIN)
    end = text.find(END)
    if begin < 0 or end < 0 or end < begin:
        return None
    return begin + len(BEGIN), end


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="refresh TRANSCRIPT.md and the README block")
    group.add_argument("--check", action="store_true", help="fail if TRANSCRIPT.md or the README block drifted")
    parser.add_argument("--quiet", action="store_true", help="do not print the transcript")
    parser.add_argument("--verbose", action="store_true",
                        help="keep every PASS line of the controller's reports (the committed transcript folds them)")
    args = parser.parse_args(argv)

    state = load_json(ROOT / "project_control/project-state.v1.json")
    if state.get("repository_role") != "PROJECT_TEMPLATE" or state["initialization"]["status"] != "NOT_STARTED":
        print("hello-squelette replays the template itself: run it from a NOT_STARTED checkout of the template.")
        return 2

    with tempfile.TemporaryDirectory(prefix="hello-squelette-") as temporary:
        transcript = play(ROOT, Path(temporary), verbose=args.verbose and not (args.write or args.check))
    full = transcript.render_full()
    excerpt = transcript.render_excerpt()

    if args.write:
        TRANSCRIPT.write_text(full, encoding="utf-8")
        text = README.read_text(encoding="utf-8")
        span = readme_block(text)
        if span is None:
            # Without the markers there is nothing to keep honest: refuse rather than write half.
            print(f"README.md has no {BEGIN} … {END} block: TRANSCRIPT.md written, but the README "
                  "block cannot be refreshed. Restore the two markers.")
            return 1
        README.write_text(text[:span[0]] + "\n" + excerpt + text[span[1]:], encoding="utf-8")
        print(f"written: {TRANSCRIPT.relative_to(ROOT)} and the README block")
        return 0

    if args.check:
        drift = []
        if not TRANSCRIPT.exists() or TRANSCRIPT.read_text(encoding="utf-8") != full:
            drift.append(str(TRANSCRIPT.relative_to(ROOT)))
        text = README.read_text(encoding="utf-8")
        span = readme_block(text)
        if span is None:
            # A missing block used to skip the check silently: removing two comments disabled
            # the very guarantee the README announces on its first screen.
            drift.append(f"README.md (no {BEGIN} … {END} block)")
        elif text[span[0]:span[1]] != "\n" + excerpt:
            drift.append("README.md (hello-squelette block)")
        if drift:
            print("DRIFT: " + ", ".join(drift) + " — regenerate with: python3 -B examples/hello-squelette/demo.py --write")
            return 1
        print("hello-squelette: TRANSCRIPT.md and the README block match the controller's output.")
        return 0

    if not args.quiet:
        print(full)
    return 0


if __name__ == "__main__":
    sys.exit(main())
